- name: create ec2 & r53
  hosts: localhost
  connection: local
  vars:
    AMI_ID: ami-09c813fb71547fc4f
    SG_ID: sg-0c0a10aa0c127c8db
    ZONE_ID: Z0531895FHVQAQ3TAJWF
    DOMAIN_NAME: daws86s.online
    instance: 
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ SG_ID }}"
      image_id: "{{ AMI_ID }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instance }}"
    register: ec2_output

  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output}}"
      
  - name: print public_ip
    ansible.builtin.debug:
      msg: "public ip of {{ item.item }} is {{ item.instance.public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print private_ip
    ansible.builtin.debug:
      msg: "private IP of {{ item.item }} is {{ item.instance.private_ip_addresses }}"
    loop: "{{ ec2_output.results }}"